name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  push:
    tags:
      - 'v*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build app
      run: ./gradlew assembleDebug assembleAndroidTest

    - name: Run instrumentation tests
      uses: emulator-wtf/run-tests@v0.9.10
      with:
        api-token: ${{ secrets.EW_API_TOKEN }}
        app: app/build/outputs/apk/debug/app-debug.apk
        test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        outputs-dir: build/test-results

    - name: Publish test report
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report-paths: 'build/test-results/**/*.xml'

  release:
    runs-on: ubuntu-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        release_name: "Release ${{ github.ref }}"
        body: "Release for version {{ github.ref }}."
        draft: false
        prerelease: false
        files: app/build/outputs/apk/release/app-release.apk
