name: CI/CD Pipeline

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: '34'
        target: 'android-34'
        components: |
          platform-tools
          build-tools;34.0.3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Start Android Emulator
      run: |
        echo "Starting emulator..."
        $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio &
        timeout 60 sh -c 'while [ ! -f $ANDROID_HOME/emulator/emulator.lock ]; do sleep 1; done'
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run instrumentation tests
      run: ./gradlew connectedAndroidTest
