name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build app
      run: ./gradlew assembleDebug assembleAndroidTest

    - name: Run instrumentation tests
      uses: emulator-wtf/run-tests@v0.9.10
      with:
        api-token: ${{ secrets.EW_API_TOKEN }}
        app: app/build/outputs/apk/debug/app-debug.apk
        test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        outputs-dir: build/test-results

    - name: Publish test report
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report-paths: 'build/test-results/**/*.xml'

  release:
    runs-on: ubuntu-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      uses: ilharp/sign-android-release@v1
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        buildToolsVersion: 33.0.0

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: release.apk
        path: ${{steps.sign_app.outputs.signedFile}}

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        tag: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.sign_app.outputs.signedFile }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
